---
swagger: 2.0
info:
  description: |
    This is a schema for node-aws rs school.
  version: 1.0.0
  title: node-aws book store
host: ojlkuvsx07.execute-api.eu-west-1.amazonaws.com
basePath: /dev
tags:
- name: products
  description: books data
schemes:
- https
paths:
  /product/{productId}:
    get:
      tags:
      - products
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        type: string
        format: uuid
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/Product'
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
  /products:
    get:
      tags:
      - products
      summary: list of products
      description: Returns all products
      operationId: getAllProducts
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
    post:
      tags:
      - products
      summary: create product
      description: Create new book
      operationId: createProduct
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: product
        description: Book data
        required: false
        schema:
          type: object
          required:
          - count
          - price
          - title
          properties:
            title:
              type: string
              default: First book
            description:
              type: string
              default: No very long description of the book
            count:
              type: integer
            price:
              type: integer
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
definitions:
  Product:
    type: object
    required:
    - count
    - id
    - title
    properties:
      id:
        type: string
        format: uuid
      title:
        type: string
        example: First book
      description:
        type: string
        example: Short Book Description
      price:
        type: number
        example: 3.3
      count:
        type: integer
        format: int64
