service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*
    - Effect: 'Allow'
      Action:
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}
    - Effect: 'Allow'
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:eu-west-1:759177250399:product-service-queue
        # FIXME

plugins:
  - serverless-dotenv-plugin

functions:
  importProductsFile:
    handler: handlers.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: True
          authorizer:
            name: basicAuthorizer
            arn: ${cf:authorization-service-${self:provider.stage}.AuthorizationLambdaArn}
#            arn:
#              !Join
#              - ':'
#              - - 'arn:aws:lambda'
#                - !Ref AWS::Region
#                - !Ref AWS::AccountId
#                - 'function:authorization-service-dev-basicAuthorizer'
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token

  importFileParser:
    handler: handlers.importFileParser
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: ${self:provider.environment.S3_BUCKET_NAME}
          # bucket: ${self:custom.s3FilesBucketName}
          rules:
            - prefix: uploaded/
          existing: true
  listParsedFiles:
    handler: handlers.listParsedFiles
    events:
      - http:
          path: list
          method: get
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
