service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*
    - Effect: 'Allow'
      Action:
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}
    - Effect: 'Allow'
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:eu-west-1:759177250399:product-service-queue
        # FIXME

plugins:
  - serverless-dotenv-plugin

functions:
  importProductsFile:
    handler: handlers.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                  name: true,
  importFileParser:
    handler: handlers.importFileParser
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: ${self:provider.environment.S3_BUCKET_NAME}
          # bucket: ${self:custom.s3FilesBucketName}
          rules:
            - prefix: uploaded/
          existing: true
  listParsedFiles:
    handler: handlers.listParsedFiles
    events:
      - http:
          path: list
          method: get
          cors: true
