service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::node-aws-files-bucket/*"

plugins:

custom:
  s3FilesBucketName: node-aws-files-bucket

functions:
  importProductsFile:
    handler: handlers.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                  name: true,
  importFileParser:
    handler: handlers.importFileParser
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: ${self:custom.s3FilesBucketName}
          rules:
            - prefix: uploaded/
          existing: true
